app:
  config:
    name: 'mistral-streamlit-app'

llm:
  provider: huggingface
  config:
    model: 'mmistralai/Mistral-7B-Instruct-v0.2'
    temperature: 0.1
    max_tokens: 250
    top_p: 0.1
    stream: true

embedder:
  provider: huggingface
  config:
    model: 'sentence-transformers/all-mpnet-base-v2'
